language: go

sudo: required
dist: xenial

env:
  - GO111MODULE=on

go:
  - 1.12.x
  - 1.11.x
  - master
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

install:
  - go get github.com/mattn/goveralls

script:
  - make test

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
