// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package application

import (
	service "github.com/euskadi31/go-service"
	mock "github.com/stretchr/testify/mock"
)

// MockServiceProvider is an autogenerated mock type for the ServiceProvider type
type MockServiceProvider struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *MockServiceProvider) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Register provides a mock function with given fields: app
func (_m *MockServiceProvider) Register(app service.Container) {
	_m.Called(app)
}
